clusters:
  - name: control
    endpoints:
      - control
  - name: app
    endpoints:
      - leader-address
      - replica-address
routes:
  - path: "/admin"
    clusters:
      - control
  - path: "*"
    clusters:
      - app
      - control
health_check_interval: 3