clusters:
  - name: control
    endpoints:
      - http://localhost:3000
  - name: app
    endpoints:
      - http://www.google.com
      - http://www.youtube.com
      # - leader-address
      # - replica-address
routes:
  - path: "/admin"
    clusters:
      - control
  - path: "/"
    clusters:
      - app
      # - control
health_check_interval: 3
port: 7000