clusters:
  - name: control
    endpoints:
      - http://127.0.0.1:3000
  - name: app
    endpoints: # DON'T FORGET PROTOCOL SEGMENT
      # - http://www.google.com
      # - http://www.youtube.com

      - http://127.0.0.1:8081
      - http://127.0.0.1:8082
      # - leader-address
      # - replica-address
db_endpoints:
  - name: app_1
    host: 127.0.0.1:3307
    table_name: patients
    db_name: testdb
  - name: app_2
    host: 127.0.0.1:3308
    table_name: patients
    db_name: testdb
routes:
  - path: "/admin"
    clusters:
      - control
  - path: "/"
    clusters:
      # - app
      - control # control has data_sync, which will cache POST request
health_check_interval: 3
data_sync_interval: 3
port: 7000
