clusters:
  - name: control
    endpoints:
      - http://localhost:3000
  - name: app
    endpoints: # DON'T FORGET PROTOCOL SEGMENT
      # - http://www.google.com
      # - http://www.youtube.com

      - http://127.0.0.1:8081
      - http://127.0.0.1:8082
      # - leader-address
      # - replica-address
routes:
  - path: "/admin"
    clusters:
      - control
  - path: "/"
    clusters:
      - app
      - control # control has data_sync, which will cache POST request
health_check_interval: 3
data_sync_interval: 3
port: 7000