clusters:
  - name: control
    endpoints:
      - http://127.0.0.1:3000
  - name: app
    endpoints: # DON'T FORGET PROTOCOL SEGMENT
      - http://127.0.0.1:8080
      - http://127.0.0.1:8081
routes:
  - path: "/admin"
    clusters:
      - control
  - path: "/"
    clusters:
      - app
      - control # control has data_sync, which will cache POST request
health_check_interval: 3
data_sync_interval: 3
host_ip: 127.0.0.1
port: 7000
proxy_control_port: 6999
